services:
  - type: web
    name: turkish-movie-review-sentiment
    env: python
    buildCommand: "pip install setuptools==82.0.0 && pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
