services:
  - type: web
    name: turkish-movie-review-sentiment
    env: python
    buildCommand: "bash scripts/render_build.sh"
      startCommand: "bash start.sh"
      envVars:
        - key: PYTHON_VERSION
          value: "3.11.9"